---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-seaweed-seaweedfs-com-v1-seaweed
  failurePolicy: Fail
  name: mseaweed.kb.io
  rules:
  - apiGroups:
    - seaweed.seaweedfs.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - seaweeds
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-seaweed-seaweedfs-com-v1-seaweed
  failurePolicy: Fail
  name: vseaweed.kb.io
  rules:
  - apiGroups:
    - seaweed.seaweedfs.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - seaweeds
  sideEffects: None
